name = "calculator-packaging"
main = "_worker.js"
compatibility_date = "2024-01-01"

[vars]
GOOGLE_API_KEY = "AIzaSyAozhGc9aqcIDx99TSOG7c7bCqqyavbJCg"

[[kv_namespaces]]
binding = "LOGS"
id = "LOGS"
preview_id = "LOGS"

[[kv_namespaces]]
binding = "ORDERS_KB"
id = "ORDERS_KB"
preview_id = "ORDERS_KB"

[site]
bucket = "dist"

[build]
command = "npm run build"
upload.format = "service-worker"
